version: "2"

run:
  go: "1.26"
  timeout: 10m
  allow-parallel-runners: true

output:
  formats:
    text:
      path: stdout
      colors: true
      print-linter-name: true
      print-issued-lines: true

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    tagliatelle:
      case:
        rules:
          json: snake

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

formatters:
  enable:
    - goimports
  exclusions:
    generated: strict
